# Generated by Django 5.1.4 on 2024-12-26 11:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_socialmedia_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedia',
            name='icon',
            field=models.FileField(upload_to='social_media/icons/', validators=[django.core.validators.FileExtensionValidator(['svg'])]),
        ),
    ]
